name: JJTS Test Streams
favicon: null
layout_spectrum: 0.3372
typography_spectrum: 0.01597576611675322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#041993'
    - '#0000ff'
    - '#9e9e9e'
    - '#4e4e4e'
    - '#e2e2e2'
  brandStrength: 0.8941309447400272
  lightness: 0.2457400457933545
  saturation: 0.42863074014894664
  rhythmicContrast: 0.23053420148789883
purpose: []
