name: JJTS Test Streams
favicon: null
layout_spectrum: 0.60271
typography_spectrum: 0.87347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#041993'
    - '#0000ff'
    - '#9e9e9e'
    - '#4e4e4e'
    - '#e2e2e2'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
